---
- name: update and upgrade packages  # sudo apt upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove dependences that are not needed  # sudo apt autoremove
  become: yes
  apt:
    autoremove: yes

- name: "Node.js 13 installation"
  become: true
  shell: |
# Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
# Use n version manager (NVM) to switch to Nodejs v13.8.0
# sudo npm install -g n
# sudo n 13.8.0

# sudo apt-get install -y nodejs
# sudo apt install -y npm

- name: install dependences  # sudo apt install nodejs v13
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes


- name: install pm2  # sudo npm install pm2 -g
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

# - name: "move env variables to /etc/profile.d/"
#   become: true
#   copy:
#     src: myenv.sh
#     dest: /etc/profile.d/