---
- name: update and upgrade packages  # sudo apt upgrade
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove dependences that are not needed  # sudo apt autoremove
  become: yes
  apt:
    autoremove: yes

- name: install dependences  # sudo apt install nodejs npm
  become: true
  apt:
    name: ['nodejs', 'npm'] 
    state: latest
    update_cache: true

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save

- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz 
    dest: ~/

- name: start server with pm2
  become: yes
  shell:
    npm install
    pm2 stop default
    pm2 start npm -- start


# - name: delay process by 60 seconds
#   ansible.builtin.pause:
#     minutes: 1
# - name: Extract artifact.tar.gz into EC2 server 
#   ansible.builtin.unarchive:
#     src: ~/project/artifact.tar.gz 
#     dest: ~/
      # src: files/artifact.tar.gz
    # dest: .
# - name: npm install all
#   command: npm install
# - name: start server with pm2
#   command: pm2 start npm -- start
# - name: delay process by 60 seconds
#   ansible.builtin.pause:
#     minutes: 1