global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-13-58-127-241-us-east-1.compute.a,azonaws.com:9100']      
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: 
        secret_key: 
        port: 9100